### ISSUE TITLE
support for tags in flex-objects?

### ISSUE THREAD

**Issue by skinofthesoul** [Perlkonig/grav-plugin-tagcloud#3]
I have noticed that tagcloud only seems to use the tags from pages, not from flex-objects. That limitation may of course stem from the taxonomylist plugin, I don't know. Are there any plans to support tags from flex-objects? That would be absolutely wonderful :-)

**Comment by Perlkonig** [comment]
Thanks for reaching out. I have no idea what a flex object is. A search tells me this is only available from some plugin, which I don't use. I'm open to extending the code, but it would have to be backwards compatible, and I'm afraid I don't have the time to learn how it works. Pull requests are very welcome, but again, everything needs to be backwards compatible.

I'm closing the issue for now, but feel free to reopen if you have further information.
